nginx:
    image: nginx
    volumes:
            - ./html:/usr/share/nginx/html:ro
            - ./conf.d:/etc/nginx/conf.d
            - ./nginx/conf/certs:/etc/nginx/certs
    ports:
      - "8080:443"